config/routes.rb
Rails.application.routes.draw do

  root to: "restaurants#index"

  resources :restaurants do
    resources :reviews, only: [ :new, :create, :index ]
  end

end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"], allow_nil: false }
  validates :name, uniqueness: true, presence: true
  validates :address, presence: true

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :rating, numericality: { only_integer: true }, inclusion: { in: [0,1,2,3,4,5], allow_nil: false }
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
     @restaurant = Restaurant.find(params[:id])
  end

  def update

    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
  end



private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<h1>Edit your Restaurant</h1>

<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

 <%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>All Restaurants <i class="fa fa-cutlery" aria-hidden="true" style="color: blue;"></i>
</h1>


 <%= link_to 'New Restaurants', new_restaurant_path, class: "btn btn-primary" %>
 <%= link_to 'Edit Restaurants', new_restaurant_path, class: "btn btn-primary" %>

<% @restaurants.each do |restaurant| %>
  <h2><i class="fa fa-user-o" aria-hidden="true"></i>
<%= link_to restaurant.name, restaurant_path(restaurant.id) %></h2>
  <p><strong><i class="fa fa-map-marker" aria-hidden="true"></i>
Address:</strong> <%= restaurant.address %></p>
  <p><strong><i class="fa fa-phone" aria-hidden="true"></i>
Phone Number:</strong> <%= restaurant.phone_number %></p>
  <p><strong>Category:</strong> <%= restaurant.category %></p>
  <br>
<% end %>

app/views/restaurants/new.html.erb
<h1>Create your new restaurant</h1>


<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

 <%= link_to 'Back', restaurants_path, class: "btn btn-primary" %>

app/views/restaurants/show.html.erb
<h1>Restaurant</h1>



  <h2>Name: <%= @restaurant.name %></h2>
  <p><strong>Address:</strong> <%= @restaurant.address %></p>
  <p><strong>Phone Number:</strong> <%= @restaurant.phone_number %></p>
  <p><strong>Category:</strong> <%= @restaurant.category %></p>




<%= link_to "Delete", restaurant_path(@restaurant), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-primary" %>

<%= link_to "All Restaurants", restaurants_path, class: "btn btn-primary" %>

<%= link_to "Edit Restaurant", edit_restaurant_path(@restaurant), class: "btn btn-primary" %>

<%= link_to "Reviews", restaurant_reviews_path(@restaurant), class: "btn btn-primary" %>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/index.html.erb
<p>Review</p>

<% @review.each do |review| %>
<p><strong></strong><% review.rating %></p>
<p><strong>Content:</strong><%= review.content %></p>


<% review.rating.times do %>
  <i class="fa fa-star" aria-hidden="true" font-size: 20px; style="color: yellow;"></i>
<% end %>

<% (5 - review.rating).times do %>
  <i class="fa fa-star" aria-hidden="true""></i>
<% end %>

<% end %>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>